import type { NextPage } from 'next'
import ButtonWeDidNotWrite from './ButtonWeDidNotWrite'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import LeverGame from './LeverGame'
import Room from './Room'
import { useQuery, useMutation } from '../convex/_generated/react'
import { useCallback } from 'react'

const Home: NextPage = () => {
  const counter = useQuery('getCounter', 'clicks') ?? 0
  const increment = useMutation('incrementCounter')
  const incrementByOne = useCallback(() => increment('clicks', 1), [increment])

  return (
    <div className='page'>
    <div className={styles.container}>
      <Head>
        <title>Next.js with Convex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <main className={styles.main}>
    <span className='counter'>
        <h1 className={styles.title}>
          welcome to bbb party🥳 with{' '}
          <a href="https://convex.dev">Convex</a>
        </h1>

        <p className={styles.description}>
          {"here's a fun counter, smash that button:"} {counter}
                  <ButtonWeDidNotWrite onClick={incrementByOne}>
          Add One!
        </ButtonWeDidNotWrite>

        </p>
    </span>
        <LeverGame />
    <Room />
    </main>

      <footer className={styles.footer}>
        <a
          href="https://www.convex.dev/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/convex.svg" alt="Convex Logo" width={90} height={18} />
          </span>
        </a>
      </footer>
    </div>
    </div>
  )
}

export default Home
